"""Artifact model — generated CR / EPIC / STORY / TASK / CTASK artefacts."""

from __future__ import annotations

import enum
import uuid

from sqlalchemy import Enum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class ArtifactType(str, enum.Enum):
    """Types of artefacts generated by the platform."""

    CR = "cr"
    EPIC = "epic"
    STORY = "story"
    TASK = "task"
    CTASK = "ctask"


class ArtifactStatus(str, enum.Enum):
    """Lifecycle of an artefact within the platform."""

    DRAFT = "draft"
    PREVIEW = "preview"
    SUBMITTED = "submitted"
    SYNCED = "synced"
    FAILED = "failed"


class Artifact(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Represents a single generated artefact (CR, Epic, Story, etc.).

    ``payload`` holds the structured body that will be pushed to Jira /
    ServiceNow / Confluence via the respective MCP client.
    """

    __tablename__ = "artifacts"

    onboarding_request_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("onboarding_requests.id", ondelete="CASCADE"),
        nullable=False,
    )
    artifact_type: Mapped[ArtifactType] = mapped_column(
        Enum(ArtifactType, name="artifact_type_enum", native_enum=False,
             values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )
    external_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    external_url: Mapped[str | None] = mapped_column(String(512), nullable=True)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    status: Mapped[ArtifactStatus] = mapped_column(
        Enum(ArtifactStatus, name="artifact_status_enum", native_enum=False,
             values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=ArtifactStatus.DRAFT,
        server_default="draft",
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    onboarding_request: Mapped[OnboardingRequest] = relationship(
        "OnboardingRequest",
        back_populates="artifacts",
    )

    def __repr__(self) -> str:
        return (
            f"<Artifact type={self.artifact_type.value!r} "
            f"status={self.status.value!r} ext_id={self.external_id!r}>"
        )


from app.models.onboarding import OnboardingRequest  # noqa: E402
